fix(zsh): change all autoload functions to be just the commands to run

diff --git a/.config/zsh/functions/fe b/.config/zsh/functions/fe
--- a/.config/zsh/functions/fe
+++ b/.config/zsh/functions/fe
@@ -1,32 +1,30 @@
 #!/usr/bin/env zsh
 
 # fe - Edit a function
-function fe() {
-    local function_name="$1"
-    local file="$HOME/.config/fish/functions/${function_name}.fish"
+local function_name="$1"
+local file="$HOME/.config/fish/functions/${function_name}.fish"
 
-    if [[ ! -e "$file" && ! $(functions "$function_name") ]]; then
-        if yn "Function $function_name does not exist. Create?"; then
-            touch "$file"
-        fi
-        return
-    fi
+if [[ ! -e "$file" && ! $(functions "$function_name") ]]; then
+if yn "Function $function_name does not exist. Create?"; then
+touch "$file"
+fi
+return
+fi
 
-    if [[ -e "$file" ]]; then
-        # Edit an autoloaded function
-        $EDITOR "$file"
-        # shellcheck disable=SC1090
-        source "$file"
-    else
-        # Edit a builtin function, save to autoload
-        funced "$function_name"
-        funcsave "$function_name"
-    fi
+if [[ -e "$file" ]]; then
+# Edit an autoloaded function
+$EDITOR "$file"
+# shellcheck disable=SC1090
+source "$file"
+else
+# Edit a builtin function, save to autoload
+funced "$function_name"
+funcsave "$function_name"
+fi
 
-    local exit_code=$?
-    if [[ $exit_code -eq 0 ]]; then
-        echo "$function_name function reloaded."
-    else
-        echo "Error reloading $function_name. Please check your syntax in $file"
-    fi
-}
+local exit_code=$?
+if [[ $exit_code -eq 0 ]]; then
+echo "$function_name function reloaded."
+else
+echo "Error reloading $function_name. Please check your syntax in $file"
+fi
diff --git a/.config/zsh/functions/path_add b/.config/zsh/functions/path_add
--- a/.config/zsh/functions/path_add
+++ b/.config/zsh/functions/path_add
@@ -1,15 +1,13 @@
 #!/usr/bin/env zsh
 
 # JDK management functions
-function path_add() {
-    local directory="$1"
-    if [[ -z "$directory" ]]; then
-        echo "Usage: path_add <directory>" >&2
-        return 1
-    elif [[ -d "$directory" ]]; then
-        export PATH="$directory:$PATH"
-    else
-        echo "Directory not found: $directory" >&2
-        return 2
-    fi
-}
+local directory="$1"
+if [[ -z "$directory" ]]; then
+echo "Usage: path_add <directory>" >&2
+return 1
+elif [[ -d "$directory" ]]; then
+export PATH="$directory:$PATH"
+else
+echo "Directory not found: $directory" >&2
+return 2
+fi
diff --git a/.config/zsh/functions/sshcopypub b/.config/zsh/functions/sshcopypub
--- a/.config/zsh/functions/sshcopypub
+++ b/.config/zsh/functions/sshcopypub
@@ -3,17 +3,17 @@
 local key_file
 
 if [[ -f ~/.ssh/id_ed25519.pub ]]; then
-    key_file=~/.ssh/id_ed25519.pub
+key_file=~/.ssh/id_ed25519.pub
 elif [[ -f ~/.ssh/id_rsa.pub ]]; then
-    key_file=~/.ssh/id_rsa.pub
+key_file=~/.ssh/id_rsa.pub
 else
-    echo "Error: No SSH key file found." >&2
-    return 1
+echo "Error: No SSH key file found." >&2
+return 1
 fi
 
 # Copy the key
 if [[ "$OSTYPE" == "darwin"* ]]; then
-    pbcopy < "$key_file"
+pbcopy < "$key_file"
 elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
-    xsel --clipboard < "$key_file"
+xsel --clipboard < "$key_file"
 fi
